spring:
  datasource:
    url: jdbc:mysql://kong.c7mdztcswhh5.ap-northeast-2.rds.amazonaws.com:3306
    username: root
    password: kongboard
    driver-class-name: com.mysql.cj.jdbc.Driver

    # h2 콘솔 설정
    h2:
      console:
        enabled: true
        path: /h2-console
    # Database setting Info